In [1]:
import pandas as pd
import os
from sqlalchemy import create_engine

In [ ]:
engine = create_engine('sqlite:///inventory.db')

In [2]:
import os

data = "/content/drive/MyDrive/DA/data"

print("Files/folders inside data:")
for item in os.listdir(data):
    print(repr(item))

Files/folders inside data:
'begin_inventory.csv'
'vendor_invoice.csv'
'end_inventory.csv'
'purchase_prices.csv'
'sales.csv'
'purchases.csv'

In [ ]:
for file in os.listdir(data):
    if '.csv' in file:
        df = pd.read_csv(os.path.join(data, file), encoding="latin1")
        print(df.shape)
        ingest_db(df,file[:-4],engine)

(206529, 9)
(5543, 10)

KeyboardInterrupt:

In [ ]:
for file in os.listdir(data):
    if file.endswith(".csv"):

        path = os.path.join(data, file)

        print("Processing:", file)

        for chunk in pd.read_csv(
            path,
            encoding="latin1",
            chunksize=50000
        ):
            ingest_db(chunk, file[:-4], engine)

        print("Finished:", file)

Processing: begin_inventory.csv
Finished: begin_inventory.csv
Processing: vendor_invoice.csv
Finished: vendor_invoice.csv
Processing: end_inventory.csv
Finished: end_inventory.csv
Processing: purchase_prices.csv
Finished: purchase_prices.csv
Processing: sales.csv
Finished: sales.csv
Processing: purchases.csv
Finished: purchases.csv

In [ ]:
def ingest_db(df,table_name,engine):
  df.to_sql(table_name,con = engine,if_exists='replace',index=False)

# **Exploratory Data Analysis**

In [4]:
import pandas as pd
import sqlite3

In [5]:
# connecting database
conn = sqlite3.connect('/content/drive/MyDrive/DA/inventory.db')

In [ ]:
tables = pd.read_sql_query("Select name From sqlite_master where type='table'",conn)
tables

                   name
0       begin_inventory
1        vendor_invoice
2         end_inventory
3       purchase_prices
4                 sales
5             purchases
6  vendor_sales_summary

In [ ]:
for table in tables['name']:
  print('-'*50,f'{table}','-'*50)
  print('Count of recordes:',pd.read_sql(f"Select count(*) as count from {table}",conn)['count'].values[0])
  display(pd.read_sql(f"Select * from {table} limit 5",conn))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of recordes: 6529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,77_TAMWORTH_2366,77,TAMWORTH,2366,Templeton Rye Whiskey,750mL,4,34.99,2024-01-01
1,77_TAMWORTH_2368,77,TAMWORTH,2368,Balvenie 17 Yr Doublewood,750mL,5,139.99,2024-01-01
2,77_TAMWORTH_2373,77,TAMWORTH,2373,Jim Beam Maple,750mL,33,13.99,2024-01-01
3,77_TAMWORTH_2374,77,TAMWORTH,2374,Tullamore Dew,1.75L,12,39.99,2024-01-01
4,77_TAMWORTH_2382,77,TAMWORTH,2382,Opihr London Dry Gin,750mL,4,27.99,2024-01-01

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of recordes: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

-------------------------------------------------- end_inventory --------------------------------------------------
Count of recordes: 24489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,73_DONCASTER_43131,73,DONCASTER,43131,Carpano Antica Formula,375mL,11,14.99,2024-12-31
1,73_DONCASTER_43143,73,DONCASTER,43143,La Puerta Torrontes,750mL,16,8.99,2024-12-31
2,73_DONCASTER_43152,73,DONCASTER,43152,Ramey Chard Sonoma Coast,750mL,15,37.99,2024-12-31
3,73_DONCASTER_43184,73,DONCASTER,43184,Writer's Block Cab Franc,750mL,12,15.99,2024-12-31
4,73_DONCASTER_43193,73,DONCASTER,43193,Dancing Bull Zabaco Cab Svgn,750mL,22,8.99,2024-12-31

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of recordes: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- sales --------------------------------------------------
Count of recordes: 25363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,8_ALNERWICK_5096,8,5096,DeKuyper Peachtree Schnapps,750mL,1,10.99,10.99,2024-12-20,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,8_ALNERWICK_5096,8,5096,DeKuyper Peachtree Schnapps,750mL,1,10.99,10.99,2024-12-21,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
2,8_ALNERWICK_5096,8,5096,DeKuyper Peachtree Schnapps,750mL,4,43.96,10.99,2024-12-23,750.0,1,3.15,12546,JIM BEAM BRANDS COMPANY
3,8_ALNERWICK_5096,8,5096,DeKuyper Peachtree Schnapps,750mL,2,21.98,10.99,2024-12-26,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
4,8_ALNERWICK_5096,8,5096,DeKuyper Peachtree Schnapps,750mL,1,10.99,10.99,2024-12-27,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- purchases --------------------------------------------------
Count of recordes: 22474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,41_LARNWICK_21573,41,21573,Casal Garcia Vinho Verde Ros,750mL,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-28,2025-01-09,2025-02-18,4.76,12,57.12,2
1,64_CESTERFIELD_23143,64,23143,Bogle Chard,750mL,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-27,2025-01-09,2025-02-18,4.65,29,134.85,2
2,24_PALPERROTH_3485,24,3485,Luksusowa Potato Vodka,1.75L,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-29,2025-01-09,2025-02-18,15.03,6,90.18,1
3,34_PITMERDEN_18974,34,18974,Pine Ridge Napa Vlly Cab Svg,750mL,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-28,2025-01-09,2025-02-18,32.67,6,196.02,2
4,74_PAENTMARWY_38011,74,38011,Yellow Tail RSV Shiraz Ausl,750mL,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-26,2025-01-09,2025-02-18,6.45,12,77.40,2

-------------------------------------------------- vendor_sales_summary --------------------------------------------------
Count of recordes: 2091

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,TotalFreight,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,17035,PERNOD RICARD USA,2589,30.76,1750,39.99,3169,97478.44,5622.52,835.78,148.0,271.95,123780.22,-91855.92,-1633.714420,0.046702,0.057680
1,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,3331,60757.44,9349.02,986.58,398.0,731.31,123780.22,-51408.42,-549.880308,0.119484,0.153874
2,8112,MOET HENNESSY USA INC,6654,27.20,750,39.99,1771,48171.20,4918.77,1279.68,123.0,13.78,48347.26,-43252.43,-879.334264,0.069452,0.102110
3,8112,MOET HENNESSY USA INC,7865,23.97,750,34.99,1950,46741.50,3044.13,874.75,87.0,9.74,48347.26,-43697.37,-1435.463334,0.044615,0.065127
4,9165,ULTRA BEVERAGE COMPANY LLP,3650,33.81,750,48.99,1279,43242.99,2547.48,783.84,52.0,40.93,68054.70,-40695.51,-1597.481040,0.040657,0.058911

In [ ]:
purchases = pd.read_sql_query("select * from purchases where VendorNumber = 4425",conn)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,41_LARNWICK_21573,41,21573,Casal Garcia Vinho Verde Ros,750mL,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-28,2025-01-09,2025-02-18,4.76,12,57.12,2
1,64_CESTERFIELD_23143,64,23143,Bogle Chard,750mL,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-27,2025-01-09,2025-02-18,4.65,29,134.85,2
2,24_PALPERROTH_3485,24,3485,Luksusowa Potato Vodka,1.75L,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-29,2025-01-09,2025-02-18,15.03,6,90.18,1
3,34_PITMERDEN_18974,34,18974,Pine Ridge Napa Vlly Cab Svg,750mL,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-28,2025-01-09,2025-02-18,32.67,6,196.02,2
4,74_PAENTMARWY_38011,74,38011,Yellow Tail RSV Shiraz Ausl,750mL,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-26,2025-01-09,2025-02-18,6.45,12,77.40,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308,15_WANBORNE_523,15,523,Castello Del Poggio Moscato,750mL,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-29,2025-01-09,2025-02-18,7.09,12,85.08,2
309,61_AETHELNEY_11219,61,11219,Josh Cellars Cab Svgn Sonoma,750mL,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-28,2025-01-09,2025-02-18,8.44,34,286.96,2
310,49_GARIGILL_44944,49,44944,Sanford Santa Rita Pnt Nr,750mL,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-27,2025-01-09,2025-02-18,14.93,12,179.16,2
311,76_DONCASTER_19948,76,19948,Josh Cellars Pnt Nr,750mL,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-28,2025-01-09,2025-02-18,10.06,12,120.72,2
312,8_ALNERWICK_37678,8,37678,Castle Rock Pnt Nr,750mL,4425,MARTIGNETTI COMPANIES,13652,2024-12-23,2024-12-27,2025-01-09,2025-02-18,6.53,12,78.36,2

In [ ]:
purchase_prices = pd.read_sql_query("select * from purchase_prices  where VendorNumber = 4425",conn)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,211,Cold River Gin,24.99,750mL,750,1,19.83,4425,MARTIGNETTI COMPANIES
1,438,Licor 43 Vanilla Liqueur,19.99,750mL,750,1,12.77,4425,MARTIGNETTI COMPANIES
2,450,Vincent Van Gogh Double Esp,24.99,750mL,750,1,19.52,4425,MARTIGNETTI COMPANIES
3,1296,Tap 357 Maple Rye Whisky,26.99,750mL,750,1,20.60,4425,MARTIGNETTI COMPANIES
4,1997,Charles Goodnight Bourbon,42.99,750mL,750,1,30.93,4425,MARTIGNETTI COMPANIES
...,...,...,...,...,...,...,...,...,...
1634,28006,Priest Ranch Coach Gun Red,69.99,750mL,750,2,48.27,4425,MARTIGNETTI COMPANIES
1635,28007,Priest Ranch Sauvignon Blanc,18.99,750mL,750,2,12.41,4425,MARTIGNETTI COMPANIES
1636,28029,DLD Syrah -Les Gosses,29.99,750mL,750,2,20.54,4425,MARTIGNETTI COMPANIES
1637,42897,Twomey Merlot Napa,58.99,750mL,750,2,39.33,4425,MARTIGNETTI COMPANIES
1638,44944,Sanford Santa Rita Pnt Nr,22.99,750mL,750,2,14.93,4425,MARTIGNETTI COMPANIES

In [ ]:
vendor_invoice = pd.read_sql_query("select * from vendor_invoice where VendorNumber = 4425",conn)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4425,MARTIGNETTI COMPANIES,2024-01-06,8160,2023-12-23,2024-02-06,24,193.80,11.38,None
1,4425,MARTIGNETTI COMPANIES,2024-01-05,8159,2023-12-23,2024-02-13,16075,185155.60,4613.45,None
2,4425,MARTIGNETTI COMPANIES,2024-01-11,8255,2023-12-30,2024-02-14,119,1460.51,6.72,None
3,4425,MARTIGNETTI COMPANIES,2024-01-18,8276,2023-12-31,2024-02-28,42400,458222.53,2336.93,Frank Delahunt
4,4425,MARTIGNETTI COMPANIES,2024-01-23,8383,2024-01-07,2024-02-29,104,987.34,4.64,None
...,...,...,...,...,...,...,...,...,...,...
77,4425,MARTIGNETTI COMPANIES,2024-12-10,13144,2024-11-20,2025-01-11,80037,815171.41,4157.37,Frank Delahunt
78,4425,MARTIGNETTI COMPANIES,2024-12-20,13298,2024-11-30,2025-01-28,51148,526973.93,2687.57,Frank Delahunt
79,4425,MARTIGNETTI COMPANIES,2024-12-24,13396,2024-12-07,2025-01-29,60932,744027.42,4092.15,Frank Delahunt
80,4425,MARTIGNETTI COMPANIES,2024-12-29,13506,2024-12-14,2025-02-12,56235,615408.50,3384.75,Frank Delahunt
81,4425,MARTIGNETTI COMPANIES,2025-01-03,13584,2024-12-19,2025-02-17,92470,1010674.21,4952.30,Frank Delahunt

In [ ]:
sales = pd.read_sql_query("select * from sales where VendorNo = 4425",conn)
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,8_ALNERWICK_523,8,523,Castello Del Poggio Moscato,750mL,1,9.99,9.99,2024-12-03,750.0,2,0.11,4425,MARTIGNETTI COMPANIES
1,8_ALNERWICK_523,8,523,Castello Del Poggio Moscato,750mL,3,29.97,9.99,2024-12-08,750.0,2,0.34,4425,MARTIGNETTI COMPANIES
2,8_ALNERWICK_523,8,523,Castello Del Poggio Moscato,750mL,1,9.99,9.99,2024-12-10,750.0,2,0.11,4425,MARTIGNETTI COMPANIES
3,8_ALNERWICK_523,8,523,Castello Del Poggio Moscato,750mL,3,29.97,9.99,2024-12-11,750.0,2,0.34,4425,MARTIGNETTI COMPANIES
4,8_ALNERWICK_523,8,523,Castello Del Poggio Moscato,750mL,2,19.98,9.99,2024-12-13,750.0,2,0.22,4425,MARTIGNETTI COMPANIES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1441,9_BLACKPOOL_8781,9,8781,Rodney Strong Cab Svgn,750mL,2,33.98,16.99,2024-12-17,750.0,2,0.22,4425,MARTIGNETTI COMPANIES
1442,9_BLACKPOOL_8781,9,8781,Rodney Strong Cab Svgn,750mL,1,16.99,16.99,2024-12-21,750.0,2,0.11,4425,MARTIGNETTI COMPANIES
1443,9_BLACKPOOL_8781,9,8781,Rodney Strong Cab Svgn,750mL,2,33.98,16.99,2024-12-22,750.0,2,0.22,4425,MARTIGNETTI COMPANIES
1444,9_BLACKPOOL_8781,9,8781,Rodney Strong Cab Svgn,750mL,2,33.98,16.99,2024-12-24,750.0,2,0.22,4425,MARTIGNETTI COMPANIES
1445,9_BLACKPOOL_8781,9,8781,Rodney Strong Cab Svgn,750mL,1,16.99,16.99,2024-12-31,750.0,2,0.11,4425,MARTIGNETTI COMPANIES

In [ ]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity  Dollars
Brand PurchasePrice
211   19.83                12   237.96
523   7.09                 35   248.15
2640  30.07                 5   150.35
2652  32.55                 6   195.30
3040  16.54                27   446.58
...                       ...      ...
45885 12.98                12   155.76
46202 6.05                 24   145.20
46429 5.80                 12    69.60
46458 7.71                 12    92.52
46764 8.21                 12    98.52

[165 rows x 2 columns]

In [ ]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [ ]:
sales.groupby('Brand')[['SalesDollars','SalesPrice','SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
211          116.96      116.96              4
438          197.89      107.94             11
450          174.93      174.93              7
523          549.45      249.75             55
2245         279.93      199.95              7
...             ...         ...            ...
46202        623.79      163.18             69
46424         99.90       59.94             10
46458        191.88      127.92             12
46762        140.90       70.95             10
46764         61.95       61.95              5

[168 rows x 3 columns]

In [ ]:
freight_summary = pd.read_sql_query("""select VendorNumber, SUM(Freight) as FreightCost
From vendor_invoice
Group By VendorNumber""",conn)

In [ ]:
freight_summary

     VendorNumber  FreightCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [ ]:
pd.read_sql_query("PRAGMA table_info(purchase_prices)", conn)

   cid            name    type  notnull dflt_value  pk
0    0           Brand  BIGINT        0       None   0
1    1     Description    TEXT        0       None   0
2    2           Price   FLOAT        0       None   0
3    3            Size    TEXT        0       None   0
4    4          Volume    TEXT        0       None   0
5    5  Classification  BIGINT        0       None   0
6    6   PurchasePrice   FLOAT        0       None   0
7    7    VendorNumber  BIGINT        0       None   0
8    8      VendorName    TEXT        0       None   0

In [ ]:
purchase_summary = pd.read_sql_query("""
SELECT
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price AS ActualPrice,
    SUM(p.Quantity) AS TotalPurchaseQuantity,
    SUM(p.Dollars) AS TotalPurchaseDollars
FROM purchases p
JOIN purchase_prices pp
ON p.Brand = pp.Brand
where p.PurchasePrice >0
GROUP BY
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price
ORDER BY TotalPurchaseDollars
""", conn)

purchase_summary

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,6213,MHW LTD,4124,0.72,50,0.99,1,0.72
1,6785,PALM BAY INTERNATIONAL INC,43432,3.94,750,5.99,1,3.94
2,9165,ULTRA BEVERAGE COMPANY LLP,15575,5.88,750,8.99,1,5.88
3,8673,STE MICHELLE WINE ESTATES,43393,5.91,750,11.99,1,5.91
4,8004,SAZERAC CO INC,5828,6.61,750,8.99,1,6.61
...,...,...,...,...,...,...,...,...
2086,9165,ULTRA BEVERAGE COMPANY LLP,3650,33.81,750,48.99,1279,43242.99
2087,8112,MOET HENNESSY USA INC,7865,23.97,750,34.99,1950,46741.50
2088,8112,MOET HENNESSY USA INC,6654,27.20,750,39.99,1771,48171.20
2089,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,3331,60757.44
2090,17035,PERNOD RICARD USA,2589,30.76,1750,39.99,3169,97478.44

In [ ]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [ ]:
pd.read_sql_query("""Select
VendorNo,
Brand,
Sum(SalesDollars) as TotalSalesDollars,
Sum(SalesPrice) as TotalSalesPrice,
Sum(SalesQuantity) as TotalSalesQuantity,
Sum(ExciseTax) as TotalExciseTax
from sales
GROUP BY VendorNo,Brand""""", conn)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,388,2034,55.98,55.98,2,1.58
1,480,126,2360.21,655.78,79,82.95
2,480,443,419.88,349.90,12,9.46
3,480,508,646.07,237.84,43,45.15
4,480,743,349.93,249.95,7,5.52
...,...,...,...,...,...,...
2490,90058,22297,69.93,49.95,7,0.78
2491,90058,22298,37.47,24.98,3,0.33
2492,90058,25126,49.95,39.96,5,0.55
2493,98450,2241,129.95,129.95,5,3.95
2494,98450,4145,118.93,101.94,7,12.87

# **Combine Table**

In [6]:
Vendor_sales_summary = pd.read_sql_query("""

WITH FreightSummary AS (

    SELECT
        VendorNumber,
        SUM(Freight) AS TotalFreight
    FROM vendor_invoice
    GROUP BY VendorNumber

),

PurchaseSummary AS (

    SELECT
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        pp.Description,
        p.PurchasePrice,
        pp.Volume,
        pp.Price AS ActualPrice,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Dollars) AS TotalPurchaseDollars

    FROM purchases p

    JOIN purchase_prices pp
        ON p.Brand = pp.Brand

    WHERE p.PurchasePrice > 0

    GROUP BY
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        pp.Description,
        p.PurchasePrice,
        pp.Volume,
        pp.Price

),

SalesSummary AS (

    SELECT
        VendorNo,
        Brand,
        SUM(SalesDollars) AS TotalSalesDollars,
        SUM(SalesPrice) AS TotalSalesPrice,
        SUM(SalesQuantity) AS TotalSalesQuantity,
        SUM(ExciseTax) AS TotalExciseTax

    FROM sales

    GROUP BY
        VendorNo,
        Brand

)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.Volume,
    ps.ActualPrice,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalSalesQuantity,
    ss.TotalExciseTax,
    fs.TotalFreight

FROM PurchaseSummary ps

LEFT JOIN SalesSummary ss
    ON ps.VendorNumber = ss.VendorNo
    AND ps.Brand = ss.Brand

LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber

ORDER BY ps.TotalPurchaseDollars DESC

""", conn)

Vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,TotalFreight
0,17035,PERNOD RICARD USA,2589,Jameson Irish Whiskey,30.76,1750,39.99,3169,97478.44,5622.52,835.78,148.0,271.95,123780.22
1,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,1750,24.99,3331,60757.44,9349.02,986.58,398.0,731.31,123780.22
2,8112,MOET HENNESSY USA INC,6654,Veuve Clicquot Brut Yellow,27.20,750,39.99,1771,48171.20,4918.77,1279.68,123.0,13.78,48347.26
3,8112,MOET HENNESSY USA INC,7865,Moet & Chandon Imperial,23.97,750,34.99,1950,46741.50,3044.13,874.75,87.0,9.74,48347.26
4,9165,ULTRA BEVERAGE COMPANY LLP,3650,Patron Silver Tequila,33.81,750,48.99,1279,43242.99,2547.48,783.84,52.0,40.93,68054.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2086,8004,SAZERAC CO INC,5828,Ryans Irish Cream,6.61,750,8.99,1,6.61,557.38,296.67,62.0,48.79,50293.62
2087,8673,STE MICHELLE WINE ESTATES,43393,Red Diamond Shiraz Wash,5.91,750,11.99,1,5.91,NaN,NaN,NaN,NaN,15919.70
2088,9165,ULTRA BEVERAGE COMPANY LLP,15575,Monte Faliesi Falanghina,5.88,750,8.99,1,5.88,NaN,NaN,NaN,NaN,68054.70
2089,6785,PALM BAY INTERNATIONAL INC,43432,Montgras RSV Svgn Bl Casabln,3.94,750,5.99,1,3.94,610.98,125.79,102.0,11.45,13605.41
2090,6213,MHW LTD,4124,Blue Chair Bay Banana Cream,0.72,50,0.99,1,0.72,69.30,16.83,70.0,3.65,9621.58

In [7]:
Vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
Volume                    object
ActualPrice              float64
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalSalesQuantity       float64
TotalExciseTax           float64
TotalFreight             float64
dtype: object

In [8]:
Vendor_sales_summary['GrossProfit'] = Vendor_sales_summary['TotalSalesDollars'] - Vendor_sales_summary['TotalPurchaseDollars']
Vendor_sales_summary['ProfitMargin'] = (Vendor_sales_summary['GrossProfit'] / Vendor_sales_summary['TotalSalesDollars']) * 100
Vendor_sales_summary['VendorName'] = Vendor_sales_summary['VendorName'].str.strip()
Vendor_sales_summary['StockTurnover'] = Vendor_sales_summary['TotalSalesQuantity'] / Vendor_sales_summary['TotalPurchaseQuantity']
Vendor_sales_summary['SalestoPurchaseRatio'] = Vendor_sales_summary['TotalSalesDollars'] / Vendor_sales_summary['TotalPurchaseDollars']

In [9]:
Vendor_sales_summary.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'Description', 'PurchasePrice',
       'Volume', 'ActualPrice', 'TotalPurchaseQuantity',
       'TotalPurchaseDollars', 'TotalSalesDollars', 'TotalSalesPrice',
       'TotalSalesQuantity', 'TotalExciseTax', 'TotalFreight', 'GrossProfit',
       'ProfitMargin', 'StockTurnover', 'SalestoPurchaseRatio'],
      dtype='object')

In [12]:
cursor.execute("DROP TABLE IF EXISTS vendor_sales_summary")
conn.commit()

In [11]:
cursor = conn.cursor()

In [13]:
cursor.execute("""create table vendor_sales_summary (
VendorNumber INT,
VendorName varchar(100),
Brand int,
Description VARCHAR(200),
PurchasePrice decimal(10,2),
Volume,
ActualPrice decimal(10,2),
TotalPurchaseQuantity int,
TotalPurchaseDollars decimal(15,2),
TotalSalesDollars decimal(15,2),
TotalSalesPrice decimal(15,2),
TotalSalesQuantity int,
TotalExciseTax decimal(15,2),
TotalFreight decimal,
GrossProfit decimal(15,2),
ProfitMargin decimal(15,2),
StockTurnover decimal(15,2),
SalestoPurchaseRatio decimal(15,2),
primary key (vendorNumber,Brand)
)""")

In [16]:
pd.read_sql_query("select * from vendor_sales_summary",conn)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,TotalFreight,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,17035,PERNOD RICARD USA,2589,Jameson Irish Whiskey,30.76,1750,39.99,3169,97478.44,5622.52,835.78,148.0,271.95,123780.22,-91855.92,-1633.714420,0.046702,0.057680
1,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,1750,24.99,3331,60757.44,9349.02,986.58,398.0,731.31,123780.22,-51408.42,-549.880308,0.119484,0.153874
2,8112,MOET HENNESSY USA INC,6654,Veuve Clicquot Brut Yellow,27.20,750,39.99,1771,48171.20,4918.77,1279.68,123.0,13.78,48347.26,-43252.43,-879.334264,0.069452,0.102110
3,8112,MOET HENNESSY USA INC,7865,Moet & Chandon Imperial,23.97,750,34.99,1950,46741.50,3044.13,874.75,87.0,9.74,48347.26,-43697.37,-1435.463334,0.044615,0.065127
4,9165,ULTRA BEVERAGE COMPANY LLP,3650,Patron Silver Tequila,33.81,750,48.99,1279,43242.99,2547.48,783.84,52.0,40.93,68054.70,-40695.51,-1597.481040,0.040657,0.058911
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2086,8004,SAZERAC CO INC,5828,Ryans Irish Cream,6.61,750,8.99,1,6.61,557.38,296.67,62.0,48.79,50293.62,550.77,98.814095,62.000000,84.323752
2087,8673,STE MICHELLE WINE ESTATES,43393,Red Diamond Shiraz Wash,5.91,750,11.99,1,5.91,NaN,NaN,NaN,NaN,15919.70,NaN,NaN,NaN,NaN
2088,9165,ULTRA BEVERAGE COMPANY LLP,15575,Monte Faliesi Falanghina,5.88,750,8.99,1,5.88,NaN,NaN,NaN,NaN,68054.70,NaN,NaN,NaN,NaN
2089,6785,PALM BAY INTERNATIONAL INC,43432,Montgras RSV Svgn Bl Casabln,3.94,750,5.99,1,3.94,610.98,125.79,102.0,11.45,13605.41,607.04,99.355134,102.000000,155.071066
2090,6213,MHW LTD,4124,Blue Chair Bay Banana Cream,0.72,50,0.99,1,0.72,69.30,16.83,70.0,3.65,9621.58,68.58,98.961039,70.000000,96.250000

In [15]:
Vendor_sales_summary.to_sql('vendor_sales_summary',conn, if_exists='replace',index = False)

2091

In [ ]:
pd.read_sql_query(
    "PRAGMA table_info(vendor_sales_summary)",
    conn
)

    cid                   name     type  notnull dflt_value  pk
0     0           VendorNumber  INTEGER        0       None   0
1     1             VendorName     TEXT        0       None   0
2     2                  Brand  INTEGER        0       None   0
3     3            Description     TEXT        0       None   0
4     4          PurchasePrice     REAL        0       None   0
5     5                 Volume     TEXT        0       None   0
6     6            ActualPrice     REAL        0       None   0
7     7  TotalPurchaseQuantity  INTEGER        0       None   0
8     8   TotalPurchaseDollars     REAL        0       None   0
9     9      TotalSalesDollars     REAL        0       None   0
10   10        TotalSalesPrice     REAL        0       None   0
11   11     TotalSalesQuantity     REAL        0       None   0
12   12         TotalExciseTax     REAL        0       None   0
13   13           TotalFreight     REAL        0       None   0
14   14            GrossProfit     REAL        0       None   0
15   15           ProfitMargin     REAL        0       None   0
16   16          StockTurnover     REAL        0       None   0
17   17   SalestoPurchaseRatio     REAL        0       None   0

In [ ]:
print(conn.execute("PRAGMA database_list").fetchall())

[(0, 'main', '/content/drive/MyDrive/DA/inventory.db')]

In [ ]:
pd.read_sql_query("""
SELECT VendorNumber, VendorName, Brand, Description
FROM vendor_sales_summary
LIMIT 10
""", conn)

   VendorNumber                  VendorName  Brand                 Description
0         17035           PERNOD RICARD USA   2589       Jameson Irish Whiskey
1         17035           PERNOD RICARD USA   8068            Absolut 80 Proof
2          8112       MOET HENNESSY USA INC   6654  Veuve Clicquot Brut Yellow
3          8112       MOET HENNESSY USA INC   7865     Moet & Chandon Imperial
4          9165  ULTRA BEVERAGE COMPANY LLP   3650       Patron Silver Tequila
5          8004              SAZERAC CO INC   5138    Fireball Cinnamon Whisky
6         17035           PERNOD RICARD USA   2585       Jameson Irish Whiskey
7          8112       MOET HENNESSY USA INC   4689     Hennessy Privilege VSOP
8          7245        PROXIMO SPIRITS INC.   3802          Three Olives Vodka
9         17035           PERNOD RICARD USA   5364                      Kahlua